/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./ZephyrusMain.types";
import * as _1 from "./ZephyrusMain.client";
import * as _2 from "./ZephyrusMain.message-composer";
export namespace contracts {
  export const ZephyrusMain = {
    ..._0,
    ..._1,
    ..._2
  };
}