/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Decimal, InstantiateMsg, ExecuteMsg, Binary, BuildVesselParams, VesselsToHarbor, Cw721ReceiveMsg, QueryMsg, Addr, ConstantsResponse, Constants, HydroConfig, VesselsResponse, Vessel, VesselHarborResponse, VesselHarborInfo, VesselHarbor, VotingPowerResponse } from "./ZephyrusMain.types";
export interface ZephyrusMainReadOnlyInterface {
  contractAddress: string;
  votingPower: () => Promise<VotingPowerResponse>;
  vesselsByOwner: ({
    limit,
    owner,
    startIndex
  }: {
    limit?: number;
    owner: string;
    startIndex?: number;
  }) => Promise<VesselsResponse>;
  vesselsByHydromancer: ({
    hydromancerAddr,
    limit,
    startIndex
  }: {
    hydromancerAddr: string;
    limit?: number;
    startIndex?: number;
  }) => Promise<VesselsResponse>;
  constants: () => Promise<ConstantsResponse>;
  vesselsHarbor: ({
    lockIds,
    roundId,
    trancheId
  }: {
    lockIds: number[];
    roundId: number;
    trancheId: number;
  }) => Promise<VesselHarborResponse>;
}
export class ZephyrusMainQueryClient implements ZephyrusMainReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.votingPower = this.votingPower.bind(this);
    this.vesselsByOwner = this.vesselsByOwner.bind(this);
    this.vesselsByHydromancer = this.vesselsByHydromancer.bind(this);
    this.constants = this.constants.bind(this);
    this.vesselsHarbor = this.vesselsHarbor.bind(this);
  }
  votingPower = async (): Promise<VotingPowerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      voting_power: {}
    });
  };
  vesselsByOwner = async ({
    limit,
    owner,
    startIndex
  }: {
    limit?: number;
    owner: string;
    startIndex?: number;
  }): Promise<VesselsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vessels_by_owner: {
        limit,
        owner,
        start_index: startIndex
      }
    });
  };
  vesselsByHydromancer = async ({
    hydromancerAddr,
    limit,
    startIndex
  }: {
    hydromancerAddr: string;
    limit?: number;
    startIndex?: number;
  }): Promise<VesselsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vessels_by_hydromancer: {
        hydromancer_addr: hydromancerAddr,
        limit,
        start_index: startIndex
      }
    });
  };
  constants = async (): Promise<ConstantsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      constants: {}
    });
  };
  vesselsHarbor = async ({
    lockIds,
    roundId,
    trancheId
  }: {
    lockIds: number[];
    roundId: number;
    trancheId: number;
  }): Promise<VesselHarborResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vessels_harbor: {
        lock_ids: lockIds,
        round_id: roundId,
        tranche_id: trancheId
      }
    });
  };
}
export interface ZephyrusMainInterface extends ZephyrusMainReadOnlyInterface {
  contractAddress: string;
  sender: string;
  buildVessel: ({
    receiver,
    vessels
  }: {
    receiver?: string;
    vessels: BuildVesselParams[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateVesselsClass: ({
    hydroLockDuration,
    hydroLockIds
  }: {
    hydroLockDuration: number;
    hydroLockIds: number[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  autoMaintain: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  modifyAutoMaintenance: ({
    autoMaintenance,
    hydroLockIds
  }: {
    autoMaintenance: boolean;
    hydroLockIds: number[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pauseContract: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpauseContract: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  decommissionVessels: ({
    hydroLockIds
  }: {
    hydroLockIds: number[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  hydromancerVote: ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  userVote: ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  receiveNft: ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  changeHydromancer: ({
    hydroLockIds,
    hydromancerId,
    trancheId
  }: {
    hydroLockIds: number[];
    hydromancerId: number;
    trancheId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ZephyrusMainClient extends ZephyrusMainQueryClient implements ZephyrusMainInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.buildVessel = this.buildVessel.bind(this);
    this.updateVesselsClass = this.updateVesselsClass.bind(this);
    this.autoMaintain = this.autoMaintain.bind(this);
    this.modifyAutoMaintenance = this.modifyAutoMaintenance.bind(this);
    this.pauseContract = this.pauseContract.bind(this);
    this.unpauseContract = this.unpauseContract.bind(this);
    this.decommissionVessels = this.decommissionVessels.bind(this);
    this.hydromancerVote = this.hydromancerVote.bind(this);
    this.userVote = this.userVote.bind(this);
    this.receiveNft = this.receiveNft.bind(this);
    this.changeHydromancer = this.changeHydromancer.bind(this);
  }
  buildVessel = async ({
    receiver,
    vessels
  }: {
    receiver?: string;
    vessels: BuildVesselParams[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      build_vessel: {
        receiver,
        vessels
      }
    }, fee, memo, _funds);
  };
  updateVesselsClass = async ({
    hydroLockDuration,
    hydroLockIds
  }: {
    hydroLockDuration: number;
    hydroLockIds: number[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_vessels_class: {
        hydro_lock_duration: hydroLockDuration,
        hydro_lock_ids: hydroLockIds
      }
    }, fee, memo, _funds);
  };
  autoMaintain = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      auto_maintain: {}
    }, fee, memo, _funds);
  };
  modifyAutoMaintenance = async ({
    autoMaintenance,
    hydroLockIds
  }: {
    autoMaintenance: boolean;
    hydroLockIds: number[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      modify_auto_maintenance: {
        auto_maintenance: autoMaintenance,
        hydro_lock_ids: hydroLockIds
      }
    }, fee, memo, _funds);
  };
  pauseContract = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause_contract: {}
    }, fee, memo, _funds);
  };
  unpauseContract = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause_contract: {}
    }, fee, memo, _funds);
  };
  decommissionVessels = async ({
    hydroLockIds
  }: {
    hydroLockIds: number[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      decommission_vessels: {
        hydro_lock_ids: hydroLockIds
      }
    }, fee, memo, _funds);
  };
  hydromancerVote = async ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      hydromancer_vote: {
        tranche_id: trancheId,
        vessels_harbors: vesselsHarbors
      }
    }, fee, memo, _funds);
  };
  userVote = async ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      user_vote: {
        tranche_id: trancheId,
        vessels_harbors: vesselsHarbors
      }
    }, fee, memo, _funds);
  };
  receiveNft = async ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive_nft: {
        msg,
        sender,
        token_id: tokenId
      }
    }, fee, memo, _funds);
  };
  changeHydromancer = async ({
    hydroLockIds,
    hydromancerId,
    trancheId
  }: {
    hydroLockIds: number[];
    hydromancerId: number;
    trancheId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_hydromancer: {
        hydro_lock_ids: hydroLockIds,
        hydromancer_id: hydromancerId,
        tranche_id: trancheId
      }
    }, fee, memo, _funds);
  };
}