/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  default_hydromancer_address: string;
  default_hydromancer_commission_rate: Decimal;
  default_hydromancer_name: string;
  hydro_contract_address: string;
  tribute_contract_address: string;
  whitelist_admins: string[];
}
export type ExecuteMsg = {
  build_vessel: {
    receiver?: string | null;
    vessels: BuildVesselParams[];
  };
} | {
  update_vessels_class: {
    hydro_lock_duration: number;
    hydro_lock_ids: number[];
  };
} | {
  auto_maintain: {};
} | {
  modify_auto_maintenance: {
    auto_maintenance: boolean;
    hydro_lock_ids: number[];
  };
} | {
  pause_contract: {};
} | {
  unpause_contract: {};
} | {
  decommission_vessels: {
    hydro_lock_ids: number[];
  };
};
export interface BuildVesselParams {
  auto_maintenance: boolean;
  hydromancer_id: number;
  lock_duration: number;
}
export type QueryMsg = {
  voting_power: {};
} | {
  vessels_by_owner: {
    limit?: number | null;
    owner: string;
    start_index?: number | null;
  };
} | {
  vessels_by_hydromancer: {
    hydromancer_addr: string;
    limit?: number | null;
    start_index?: number | null;
  };
} | {
  is_contract_paused: {};
};
export type Boolean = boolean;
export interface VesselsResponse {
  limit: number;
  start_index: number;
  total: number;
  vessels: Vessel[];
}
export interface Vessel {
  auto_maintenance: boolean;
  class_period: number;
  hydro_lock_id: number;
  hydromancer_id: number;
  tokenized_share_record_id: number;
}
export interface VotingPowerResponse {
  voting_power: number;
}