/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { Decimal, InstantiateMsg, ExecuteMsg, Binary, VesselsToHarbor, Cw721ReceiveMsg, QueryMsg, Addr, ConstantsResponse, Constants, HydroConfig, VesselsResponse, Vessel, VesselHarborResponse, VesselHarborInfo, VesselHarbor, Uint128, VesselsRewardsResponse, RewardInfo, Coin, VotedProposalsResponse } from "./ZephyrusMain.types";
export interface ZephyrusMainReadOnlyInterface {
  contractAddress: string;
  vesselsByOwner: ({
    limit,
    owner,
    startIndex
  }: {
    limit?: number;
    owner: string;
    startIndex?: number;
  }) => Promise<VesselsResponse>;
  vesselsByHydromancer: ({
    hydromancerAddr,
    limit,
    startIndex
  }: {
    hydromancerAddr: string;
    limit?: number;
    startIndex?: number;
  }) => Promise<VesselsResponse>;
  constants: () => Promise<ConstantsResponse>;
  vesselsHarbor: ({
    lockIds,
    roundId,
    trancheId
  }: {
    lockIds: number[];
    roundId: number;
    trancheId: number;
  }) => Promise<VesselHarborResponse>;
  vesselsRewards: ({
    roundId,
    trancheId,
    userAddress,
    vesselIds
  }: {
    roundId: number;
    trancheId: number;
    userAddress: string;
    vesselIds: number[];
  }) => Promise<VesselsRewardsResponse>;
  votedProposals: ({
    roundId
  }: {
    roundId: number;
  }) => Promise<VotedProposalsResponse>;
}
export class ZephyrusMainQueryClient implements ZephyrusMainReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.vesselsByOwner = this.vesselsByOwner.bind(this);
    this.vesselsByHydromancer = this.vesselsByHydromancer.bind(this);
    this.constants = this.constants.bind(this);
    this.vesselsHarbor = this.vesselsHarbor.bind(this);
    this.vesselsRewards = this.vesselsRewards.bind(this);
    this.votedProposals = this.votedProposals.bind(this);
  }
  vesselsByOwner = async ({
    limit,
    owner,
    startIndex
  }: {
    limit?: number;
    owner: string;
    startIndex?: number;
  }): Promise<VesselsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vessels_by_owner: {
        limit,
        owner,
        start_index: startIndex
      }
    });
  };
  vesselsByHydromancer = async ({
    hydromancerAddr,
    limit,
    startIndex
  }: {
    hydromancerAddr: string;
    limit?: number;
    startIndex?: number;
  }): Promise<VesselsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vessels_by_hydromancer: {
        hydromancer_addr: hydromancerAddr,
        limit,
        start_index: startIndex
      }
    });
  };
  constants = async (): Promise<ConstantsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      constants: {}
    });
  };
  vesselsHarbor = async ({
    lockIds,
    roundId,
    trancheId
  }: {
    lockIds: number[];
    roundId: number;
    trancheId: number;
  }): Promise<VesselHarborResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vessels_harbor: {
        lock_ids: lockIds,
        round_id: roundId,
        tranche_id: trancheId
      }
    });
  };
  vesselsRewards = async ({
    roundId,
    trancheId,
    userAddress,
    vesselIds
  }: {
    roundId: number;
    trancheId: number;
    userAddress: string;
    vesselIds: number[];
  }): Promise<VesselsRewardsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vessels_rewards: {
        round_id: roundId,
        tranche_id: trancheId,
        user_address: userAddress,
        vessel_ids: vesselIds
      }
    });
  };
  votedProposals = async ({
    roundId
  }: {
    roundId: number;
  }): Promise<VotedProposalsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      voted_proposals: {
        round_id: roundId
      }
    });
  };
}
export interface ZephyrusMainInterface extends ZephyrusMainReadOnlyInterface {
  contractAddress: string;
  sender: string;
  takeControl: ({
    vesselIds
  }: {
    vesselIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  unvote: ({
    trancheId,
    vesselIds
  }: {
    trancheId: number;
    vesselIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateVesselsClass: ({
    hydroLockDuration,
    hydroLockIds
  }: {
    hydroLockDuration: number;
    hydroLockIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  autoMaintain: ({
    classPeriod,
    limit,
    startFromVesselId
  }: {
    classPeriod: number;
    limit?: number;
    startFromVesselId?: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  modifyAutoMaintenance: ({
    autoMaintenance,
    hydroLockIds
  }: {
    autoMaintenance: boolean;
    hydroLockIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  pauseContract: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  unpauseContract: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  decommissionVessels: ({
    hydroLockIds
  }: {
    hydroLockIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  hydromancerVote: ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  userVote: ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  receiveNft: ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  changeHydromancer: ({
    hydroLockIds,
    hydromancerId,
    trancheId
  }: {
    hydroLockIds: number[];
    hydromancerId: number;
    trancheId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  claim: ({
    roundId,
    trancheId,
    tributeIds,
    vesselIds
  }: {
    roundId: number;
    trancheId: number;
    tributeIds: number[];
    vesselIds: number[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  setAdminAddresses: ({
    admins
  }: {
    admins: string[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateConstants: ({
    commissionRate,
    commissionRecipient,
    defaultHydromancerId,
    minTokensPerVessel
  }: {
    commissionRate?: Decimal;
    commissionRecipient?: string;
    defaultHydromancerId?: number;
    minTokensPerVessel?: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  hydroGovVoteSingle: ({
    proposalId,
    vote
  }: {
    proposalId: number;
    vote: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  returnToHydro: ({
    vesselId
  }: {
    vesselId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class ZephyrusMainClient extends ZephyrusMainQueryClient implements ZephyrusMainInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.takeControl = this.takeControl.bind(this);
    this.unvote = this.unvote.bind(this);
    this.updateVesselsClass = this.updateVesselsClass.bind(this);
    this.autoMaintain = this.autoMaintain.bind(this);
    this.modifyAutoMaintenance = this.modifyAutoMaintenance.bind(this);
    this.pauseContract = this.pauseContract.bind(this);
    this.unpauseContract = this.unpauseContract.bind(this);
    this.decommissionVessels = this.decommissionVessels.bind(this);
    this.hydromancerVote = this.hydromancerVote.bind(this);
    this.userVote = this.userVote.bind(this);
    this.receiveNft = this.receiveNft.bind(this);
    this.changeHydromancer = this.changeHydromancer.bind(this);
    this.claim = this.claim.bind(this);
    this.setAdminAddresses = this.setAdminAddresses.bind(this);
    this.updateConstants = this.updateConstants.bind(this);
    this.hydroGovVoteSingle = this.hydroGovVoteSingle.bind(this);
    this.returnToHydro = this.returnToHydro.bind(this);
  }
  takeControl = async ({
    vesselIds
  }: {
    vesselIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      take_control: {
        vessel_ids: vesselIds
      }
    }, fee_, memo_, funds_);
  };
  unvote = async ({
    trancheId,
    vesselIds
  }: {
    trancheId: number;
    vesselIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unvote: {
        tranche_id: trancheId,
        vessel_ids: vesselIds
      }
    }, fee_, memo_, funds_);
  };
  updateVesselsClass = async ({
    hydroLockDuration,
    hydroLockIds
  }: {
    hydroLockDuration: number;
    hydroLockIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_vessels_class: {
        hydro_lock_duration: hydroLockDuration,
        hydro_lock_ids: hydroLockIds
      }
    }, fee_, memo_, funds_);
  };
  autoMaintain = async ({
    classPeriod,
    limit,
    startFromVesselId
  }: {
    classPeriod: number;
    limit?: number;
    startFromVesselId?: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      auto_maintain: {
        class_period: classPeriod,
        limit,
        start_from_vessel_id: startFromVesselId
      }
    }, fee_, memo_, funds_);
  };
  modifyAutoMaintenance = async ({
    autoMaintenance,
    hydroLockIds
  }: {
    autoMaintenance: boolean;
    hydroLockIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      modify_auto_maintenance: {
        auto_maintenance: autoMaintenance,
        hydro_lock_ids: hydroLockIds
      }
    }, fee_, memo_, funds_);
  };
  pauseContract = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause_contract: {}
    }, fee_, memo_, funds_);
  };
  unpauseContract = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause_contract: {}
    }, fee_, memo_, funds_);
  };
  decommissionVessels = async ({
    hydroLockIds
  }: {
    hydroLockIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      decommission_vessels: {
        hydro_lock_ids: hydroLockIds
      }
    }, fee_, memo_, funds_);
  };
  hydromancerVote = async ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      hydromancer_vote: {
        tranche_id: trancheId,
        vessels_harbors: vesselsHarbors
      }
    }, fee_, memo_, funds_);
  };
  userVote = async ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      user_vote: {
        tranche_id: trancheId,
        vessels_harbors: vesselsHarbors
      }
    }, fee_, memo_, funds_);
  };
  receiveNft = async ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive_nft: {
        msg,
        sender,
        token_id: tokenId
      }
    }, fee_, memo_, funds_);
  };
  changeHydromancer = async ({
    hydroLockIds,
    hydromancerId,
    trancheId
  }: {
    hydroLockIds: number[];
    hydromancerId: number;
    trancheId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      change_hydromancer: {
        hydro_lock_ids: hydroLockIds,
        hydromancer_id: hydromancerId,
        tranche_id: trancheId
      }
    }, fee_, memo_, funds_);
  };
  claim = async ({
    roundId,
    trancheId,
    tributeIds,
    vesselIds
  }: {
    roundId: number;
    trancheId: number;
    tributeIds: number[];
    vesselIds: number[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {
        round_id: roundId,
        tranche_id: trancheId,
        tribute_ids: tributeIds,
        vessel_ids: vesselIds
      }
    }, fee_, memo_, funds_);
  };
  setAdminAddresses = async ({
    admins
  }: {
    admins: string[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_admin_addresses: {
        admins
      }
    }, fee_, memo_, funds_);
  };
  updateConstants = async ({
    commissionRate,
    commissionRecipient,
    defaultHydromancerId,
    minTokensPerVessel
  }: {
    commissionRate?: Decimal;
    commissionRecipient?: string;
    defaultHydromancerId?: number;
    minTokensPerVessel?: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_constants: {
        commission_rate: commissionRate,
        commission_recipient: commissionRecipient,
        default_hydromancer_id: defaultHydromancerId,
        min_tokens_per_vessel: minTokensPerVessel
      }
    }, fee_, memo_, funds_);
  };
  hydroGovVoteSingle = async ({
    proposalId,
    vote
  }: {
    proposalId: number;
    vote: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      hydro_gov_vote_single: {
        proposal_id: proposalId,
        vote
      }
    }, fee_, memo_, funds_);
  };
  returnToHydro = async ({
    vesselId
  }: {
    vesselId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      return_to_hydro: {
        vessel_id: vesselId
      }
    }, fee_, memo_, funds_);
  };
}