/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export interface InstantiateMsg {
  commission_rate: Decimal;
  commission_recipient: string;
  default_hydromancer_address: string;
  default_hydromancer_commission_rate: Decimal;
  default_hydromancer_name: string;
  hydro_contract_address: string;
  tribute_contract_address: string;
  whitelist_admins: string[];
}
export type ExecuteMsg = {
  take_control: {
    vessel_ids: number[];
  };
} | {
  unvote: {
    tranche_id: number;
    vessel_ids: number[];
  };
} | {
  update_vessels_class: {
    hydro_lock_duration: number;
    hydro_lock_ids: number[];
  };
} | {
  auto_maintain: {
    class_period: number;
    limit?: number | null;
    start_from_vessel_id?: number | null;
  };
} | {
  modify_auto_maintenance: {
    auto_maintenance: boolean;
    hydro_lock_ids: number[];
  };
} | {
  pause_contract: {};
} | {
  unpause_contract: {};
} | {
  decommission_vessels: {
    hydro_lock_ids: number[];
  };
} | {
  hydromancer_vote: {
    tranche_id: number;
    vessels_harbors: VesselsToHarbor[];
  };
} | {
  user_vote: {
    tranche_id: number;
    vessels_harbors: VesselsToHarbor[];
  };
} | {
  receive_nft: Cw721ReceiveMsg;
} | {
  change_hydromancer: {
    hydro_lock_ids: number[];
    hydromancer_id: number;
    tranche_id: number;
  };
} | {
  claim: {
    round_id: number;
    tranche_id: number;
    tribute_ids: number[];
    vessel_ids: number[];
  };
} | {
  update_commission_rate: {
    new_commission_rate: Decimal;
  };
} | {
  update_commission_recipient: {
    new_commission_recipient: string;
  };
} | {
  set_admin_addresses: {
    admins: string[];
  };
};
export type Binary = string;
export interface VesselsToHarbor {
  harbor_id: number;
  vessel_ids: number[];
}
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
}
export type QueryMsg = {
  vessels_by_owner: {
    limit?: number | null;
    owner: string;
    start_index?: number | null;
  };
} | {
  vessels_by_hydromancer: {
    hydromancer_addr: string;
    limit?: number | null;
    start_index?: number | null;
  };
} | {
  constants: {};
} | {
  vessels_harbor: {
    lock_ids: number[];
    round_id: number;
    tranche_id: number;
  };
} | {
  vessels_rewards: {
    round_id: number;
    tranche_id: number;
    user_address: string;
    vessel_ids: number[];
  };
} | {
  voted_proposals: {
    round_id: number;
  };
};
export type Addr = string;
export interface ConstantsResponse {
  constants: Constants;
}
export interface Constants {
  commission_rate: Decimal;
  commission_recipient: Addr;
  default_hydromancer_id: number;
  hydro_config: HydroConfig;
  paused_contract: boolean;
}
export interface HydroConfig {
  hydro_contract_address: Addr;
  hydro_tribute_contract_address: Addr;
}
export interface VesselsResponse {
  limit: number;
  start_index: number;
  total: number;
  vessels: Vessel[];
}
export interface Vessel {
  auto_maintenance: boolean;
  class_period: number;
  hydro_lock_id: number;
  hydromancer_id?: number | null;
  owner_id: number;
  tokenized_share_record_id?: number | null;
}
export interface VesselHarborResponse {
  vessels_harbor_info: VesselHarborInfo[];
}
export interface VesselHarborInfo {
  harbor_id?: number | null;
  vessel_id: number;
  vessel_to_harbor?: VesselHarbor | null;
}
export interface VesselHarbor {
  hydro_lock_id: number;
  steerer_id: number;
  user_control: boolean;
}
export type Uint128 = string;
export interface VesselsRewardsResponse {
  rewards: RewardInfo[];
  round_id: number;
  tranche_id: number;
}
export interface RewardInfo {
  coin: Coin;
  proposal_id: number;
  tribute_id: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface VotedProposalsResponse {
  voted_proposals: number[];
}