/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Decimal, InstantiateMsg, ExecuteMsg, Binary, VesselsToHarbor, Cw721ReceiveMsg, QueryMsg, Addr, ConstantsResponse, Constants, HydroConfig, VesselsResponse, Vessel, VesselHarborResponse, VesselHarborInfo, VesselHarbor, Uint128, VesselsRewardsResponse, RewardInfo, Coin, VotedProposalsResponse } from "./ZephyrusMain.types";
export interface ZephyrusMainMsg {
  contractAddress: string;
  sender: string;
  takeControl: ({
    vesselIds
  }: {
    vesselIds: number[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unvote: ({
    trancheId,
    vesselIds
  }: {
    trancheId: number;
    vesselIds: number[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateVesselsClass: ({
    hydroLockDuration,
    hydroLockIds
  }: {
    hydroLockDuration: number;
    hydroLockIds: number[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  autoMaintain: ({
    classPeriod,
    limit,
    startFromVesselId
  }: {
    classPeriod: number;
    limit?: number;
    startFromVesselId?: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  modifyAutoMaintenance: ({
    autoMaintenance,
    hydroLockIds
  }: {
    autoMaintenance: boolean;
    hydroLockIds: number[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pauseContract: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpauseContract: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  decommissionVessels: ({
    hydroLockIds
  }: {
    hydroLockIds: number[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  hydromancerVote: ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  userVote: ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  receiveNft: ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  changeHydromancer: ({
    hydroLockIds,
    hydromancerId,
    trancheId
  }: {
    hydroLockIds: number[];
    hydromancerId: number;
    trancheId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  claim: ({
    roundId,
    trancheId,
    tributeIds,
    vesselIds
  }: {
    roundId: number;
    trancheId: number;
    tributeIds: number[];
    vesselIds: number[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setAdminAddresses: ({
    admins
  }: {
    admins: string[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateConstants: ({
    commissionRate,
    commissionRecipient,
    defaultHydromancerId,
    minTokensPerVessel
  }: {
    commissionRate?: Decimal;
    commissionRecipient?: string;
    defaultHydromancerId?: number;
    minTokensPerVessel?: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  hydroGovVoteSingle: ({
    proposalId,
    vote
  }: {
    proposalId: number;
    vote: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  returnToHydro: ({
    vesselId
  }: {
    vesselId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class ZephyrusMainMsgComposer implements ZephyrusMainMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.takeControl = this.takeControl.bind(this);
    this.unvote = this.unvote.bind(this);
    this.updateVesselsClass = this.updateVesselsClass.bind(this);
    this.autoMaintain = this.autoMaintain.bind(this);
    this.modifyAutoMaintenance = this.modifyAutoMaintenance.bind(this);
    this.pauseContract = this.pauseContract.bind(this);
    this.unpauseContract = this.unpauseContract.bind(this);
    this.decommissionVessels = this.decommissionVessels.bind(this);
    this.hydromancerVote = this.hydromancerVote.bind(this);
    this.userVote = this.userVote.bind(this);
    this.receiveNft = this.receiveNft.bind(this);
    this.changeHydromancer = this.changeHydromancer.bind(this);
    this.claim = this.claim.bind(this);
    this.setAdminAddresses = this.setAdminAddresses.bind(this);
    this.updateConstants = this.updateConstants.bind(this);
    this.hydroGovVoteSingle = this.hydroGovVoteSingle.bind(this);
    this.returnToHydro = this.returnToHydro.bind(this);
  }
  takeControl = ({
    vesselIds
  }: {
    vesselIds: number[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          take_control: {
            vessel_ids: vesselIds
          }
        })),
        funds: _funds
      })
    };
  };
  unvote = ({
    trancheId,
    vesselIds
  }: {
    trancheId: number;
    vesselIds: number[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unvote: {
            tranche_id: trancheId,
            vessel_ids: vesselIds
          }
        })),
        funds: _funds
      })
    };
  };
  updateVesselsClass = ({
    hydroLockDuration,
    hydroLockIds
  }: {
    hydroLockDuration: number;
    hydroLockIds: number[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_vessels_class: {
            hydro_lock_duration: hydroLockDuration,
            hydro_lock_ids: hydroLockIds
          }
        })),
        funds: _funds
      })
    };
  };
  autoMaintain = ({
    classPeriod,
    limit,
    startFromVesselId
  }: {
    classPeriod: number;
    limit?: number;
    startFromVesselId?: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          auto_maintain: {
            class_period: classPeriod,
            limit,
            start_from_vessel_id: startFromVesselId
          }
        })),
        funds: _funds
      })
    };
  };
  modifyAutoMaintenance = ({
    autoMaintenance,
    hydroLockIds
  }: {
    autoMaintenance: boolean;
    hydroLockIds: number[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          modify_auto_maintenance: {
            auto_maintenance: autoMaintenance,
            hydro_lock_ids: hydroLockIds
          }
        })),
        funds: _funds
      })
    };
  };
  pauseContract = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause_contract: {}
        })),
        funds: _funds
      })
    };
  };
  unpauseContract = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause_contract: {}
        })),
        funds: _funds
      })
    };
  };
  decommissionVessels = ({
    hydroLockIds
  }: {
    hydroLockIds: number[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          decommission_vessels: {
            hydro_lock_ids: hydroLockIds
          }
        })),
        funds: _funds
      })
    };
  };
  hydromancerVote = ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          hydromancer_vote: {
            tranche_id: trancheId,
            vessels_harbors: vesselsHarbors
          }
        })),
        funds: _funds
      })
    };
  };
  userVote = ({
    trancheId,
    vesselsHarbors
  }: {
    trancheId: number;
    vesselsHarbors: VesselsToHarbor[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          user_vote: {
            tranche_id: trancheId,
            vessels_harbors: vesselsHarbors
          }
        })),
        funds: _funds
      })
    };
  };
  receiveNft = ({
    msg,
    sender,
    tokenId
  }: {
    msg: Binary;
    sender: string;
    tokenId: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          receive_nft: {
            msg,
            sender,
            token_id: tokenId
          }
        })),
        funds: _funds
      })
    };
  };
  changeHydromancer = ({
    hydroLockIds,
    hydromancerId,
    trancheId
  }: {
    hydroLockIds: number[];
    hydromancerId: number;
    trancheId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          change_hydromancer: {
            hydro_lock_ids: hydroLockIds,
            hydromancer_id: hydromancerId,
            tranche_id: trancheId
          }
        })),
        funds: _funds
      })
    };
  };
  claim = ({
    roundId,
    trancheId,
    tributeIds,
    vesselIds
  }: {
    roundId: number;
    trancheId: number;
    tributeIds: number[];
    vesselIds: number[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          claim: {
            round_id: roundId,
            tranche_id: trancheId,
            tribute_ids: tributeIds,
            vessel_ids: vesselIds
          }
        })),
        funds: _funds
      })
    };
  };
  setAdminAddresses = ({
    admins
  }: {
    admins: string[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_admin_addresses: {
            admins
          }
        })),
        funds: _funds
      })
    };
  };
  updateConstants = ({
    commissionRate,
    commissionRecipient,
    defaultHydromancerId,
    minTokensPerVessel
  }: {
    commissionRate?: Decimal;
    commissionRecipient?: string;
    defaultHydromancerId?: number;
    minTokensPerVessel?: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_constants: {
            commission_rate: commissionRate,
            commission_recipient: commissionRecipient,
            default_hydromancer_id: defaultHydromancerId,
            min_tokens_per_vessel: minTokensPerVessel
          }
        })),
        funds: _funds
      })
    };
  };
  hydroGovVoteSingle = ({
    proposalId,
    vote
  }: {
    proposalId: number;
    vote: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          hydro_gov_vote_single: {
            proposal_id: proposalId,
            vote
          }
        })),
        funds: _funds
      })
    };
  };
  returnToHydro = ({
    vesselId
  }: {
    vesselId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          return_to_hydro: {
            vessel_id: vesselId
          }
        })),
        funds: _funds
      })
    };
  };
}